/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package unidad.pkg1.practica.pkg4;

import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;

/**
 *
 * @author aula1
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgImagenes = new javax.swing.ButtonGroup();
        radImagen1 = new javax.swing.JRadioButton();
        radImagen2 = new javax.swing.JRadioButton();
        radImagen3 = new javax.swing.JRadioButton();
        radImagen4 = new javax.swing.JRadioButton();
        pnImagen = new javax.swing.JPanel();
        lblImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Unidad 1-Practica 4");
        setResizable(false);

        btgImagenes.add(radImagen1);
        radImagen1.setText("Imagen 1");
        radImagen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radImagen1ActionPerformed(evt);
            }
        });

        btgImagenes.add(radImagen2);
        radImagen2.setText("Imagen 2");
        radImagen2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radImagen2ActionPerformed(evt);
            }
        });

        btgImagenes.add(radImagen3);
        radImagen3.setText("Imagen 3");
        radImagen3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radImagen3ActionPerformed(evt);
            }
        });

        btgImagenes.add(radImagen4);
        radImagen4.setText("Imagen 4");
        radImagen4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radImagen4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnImagenLayout = new javax.swing.GroupLayout(pnImagen);
        pnImagen.setLayout(pnImagenLayout);
        pnImagenLayout.setHorizontalGroup(
            pnImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImagen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
        );
        pnImagenLayout.setVerticalGroup(
            pnImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImagen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radImagen1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(radImagen2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(radImagen3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(radImagen4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(radImagen1)
                .addGap(18, 18, 18)
                .addComponent(radImagen2)
                .addGap(18, 18, 18)
                .addComponent(radImagen3)
                .addGap(18, 18, 18)
                .addComponent(radImagen4)
                .addContainerGap(104, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void radImagen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radImagen1ActionPerformed
        if(radImagen1.isSelected());
        {
            int ancho = lblImagen.getWidth();
            int largo = lblImagen.getHeight();
            
            ImageIcon img = new ImageIcon("src/img/img1.jpg");
            Image escala = img.getImage().getScaledInstance(ancho, largo, Image.SCALE_SMOOTH);
            lblImagen.setIcon(img);
        }        
    }//GEN-LAST:event_radImagen1ActionPerformed

    private void radImagen2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radImagen2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radImagen2ActionPerformed

    private void radImagen3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radImagen3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radImagen3ActionPerformed

    private void radImagen4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radImagen4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radImagen4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgImagenes;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JPanel pnImagen;
    private javax.swing.JRadioButton radImagen1;
    private javax.swing.JRadioButton radImagen2;
    private javax.swing.JRadioButton radImagen3;
    private javax.swing.JRadioButton radImagen4;
    // End of variables declaration//GEN-END:variables
}
